<?php

/**
 * @file
 * Generated by BLT. Serves as an example of global includes.
 */

/**
 * An example global include file.
 *
 * To use this file, rename to global.settings.php.
 */

/**
* Set configuration directories
*/
$config_directories = array();
$config_directories['sync'] = $app_root . '/../config/sync';
$config_directories['blt'] = $app_root . '/../config/default';


/**
* Salt file
*/
$settings['hash_salt'] = file_get_contents($app_root . '/../salt.txt');



/**
 * Include settings files in docroot/sites/settings.
 *
 * If instead you want to add settings to a specific site, see BLT's includes
 * file in docroot/sites/{site-name}/settings/default.includes.settings.php.
 */
$additionalSettingsFiles = [
  // e.g,( DRUPAL_ROOT . "/sites/settings/foo.settings.php" )
];

foreach ($additionalSettingsFiles as $settingsFile) {
  if (file_exists($settingsFile)) {
    require $settingsFile;
  }
}
