<?php

/**
 * @file
 * Contains webny_solr_searches.module.
 */

/**
* Implements hook_views_pre_execute().
*/
function webny_solr_searches_views_pre_view($view) {
  // Filter terms /search/% page view.
  if ($view->current_display == 'webny_search_page') {
    // Set filter term id contextual filter based url value.
    if (isset($view->args[0])) {
      // Check for numeric value or name.
      if (is_numeric($view->args[0])) {
        $filter_term_id = $view->args[0];
      }
      else {
        $filter_term_name = str_replace('-', '_', $view->args[0]);
        $term = taxonomy_term_machine_name_load($filter_term_name, 'webny_filter_terms_tax');

        // Has matching term. Set a term id argument.
        if ($term) {
          $filter_term_id = $term->tid->value;
        }
      }

      if (isset($filter_term_id)) {
        $parents = \Drupal::service('entity_type.manager')
          ->getStorage('taxonomy_term')
          ->loadParents($filter_term_id);

        // Exclude child terms.
        if (!$parents) {
          $view->setArguments([$filter_term_id]);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_views_view().
 */
function webny_solr_searches_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  // Create a facet block for the page view.
  if ($view->current_display == 'webny_search_page') {
    $variables['filter_term_block'] = \Drupal::service('plugin.manager.block')
      ->createInstance('facet_block:filter_term')
      ->build();
  }

  // Create a facet block for the block view.
  if ($view->current_display == 'webny_search_block') {
    $variables['filter_term_block'] = \Drupal::service('plugin.manager.block')
      ->createInstance('facet_block:filter_term_block')
      ->build();
  }

  // Get the term name ('search_group') to display as the view title bar.
  if ($view->id() == 'webny_search') {
    // Search group is the term name used for the view's title bar.
    $search_group = \Drupal::service('entity_type.manager')
      ->getStorage('taxonomy_term')
      ->load($view->args[0])
      ->getName();

    if ($search_group) {
      $variables['search_group'] = $search_group;
    }
  }
}

/**
 * Implements hook_form_alter();
 */
function webny_solr_searches_form_alter(&$form, $form_state, $form_id) {
  $view = $form_state->getStorage('view');

  if ($form_id == 'views_exposed_form' && $view['view']->id() == 'webny_search') {
    // Add placeholder text to keyword search field.
    $form['keyword']['#attributes']['placeholder'] = t('Keyword(s)');
  }
}

/**
 * Prepares variables for paragraph templates.
 */
function webny_solr_searches_preprocess_paragraph(array &$variables) {
  $type = $variables['paragraph']->getEntityTypeId();
  $bundle = $variables['paragraph']->bundle();
  $paragraph = $variables['elements']['#paragraph'];

  // Filter terms listing handling.
  if ($type == 'paragraph' && $bundle == 'webny_filter_term_listing') {
    // Add view as the output.
    $term_id = $paragraph->webny_filter_term->getValue()[0]['target_id'];
    $variables['content']['webny_filter_term'] = views_embed_view('webny_search', 'webny_search_block', $term_id);
  }
}

// Add machine names to filter terms taxonomy post module install.
function webny_solr_searches_modules_installed($modules) {
  if (in_array('taxonomy_machine_name', $modules)) {
    $term_storage = \Drupal::service('entity_type.manager')
      ->getStorage('taxonomy_term');
    $terms = $term_storage->loadTree('webny_filter_terms_tax', 0, NULL, TRUE);

    foreach ($terms as $term) {
      // If term machine name is empty then create one.
      taxonomy_machine_name_update_term($term);
    }
  }
}
