project:
    machine_name: nysits
    prefix: NDD
    human_name: 'Web NY'
    profile:
        name: webny
        contrib: false
    local:
        protocol: http
        hostname: '${project.machine_name}.localhost'
    acquia_subname: acsfdev
    themes:
        - webny_theme
    hash_salt: NZ4pGCYwwI0kPGr5KwDkK1IgC2XOl8jFURj7q8lgAUBw6xxRXlWJNZZ
git:
    default_branch: develop
    remotes:
        - 'nysits@svn-43.enterprise-g1.hosting.acquia.com:nysits.git'
drush:
    aliases:
        remote: 01dev.dev
        remote-dev-dev: 01dev.dev
        remote-uat-prod: 01live.uat
        remote-ig-prod: 01live.ig
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}/profiles/custom/webny/themes/custom/webny_theme'
        command: ' "source ~/.bashrc && nvm use --delete-prefix 0.12.7 | ./install-node.sh" && npm run install-webny_theme'
    frontend-build:
        dir: '${docroot}/profiles/custom/webny/themes/custom/webny_theme'
        command: 'npm run build'
#    post-setup-build:
#        dir: '${docroot}/profiles/contrib/lightning'
#        command: 'npm run install-libraries'
blt:
  update:
    ignore-existing-file: '${repo.root}/scripts/blt/ignore-existing.txt'

import: '${repo.root}/blt/custom/phing/tasks/build.xml'
hosting: acsf
example.property: 'example value'

phpunit:
      failures: false

disable-targets:
  validate:
    composer: true
