bundle: webny
required:
  - workbench_moderation.moderation_state.archived
  - workbench_moderation.moderation_state.draft
  - workbench_moderation.moderation_state.needs_review
  - workbench_moderation.moderation_state.published
  - workbench_moderation.moderation_state_transition.draft_archived
  - workbench_moderation.moderation_state_transition.draft_draft
  - workbench_moderation.moderation_state_transition.draft_needs_review
  - workbench_moderation.moderation_state_transition.draft_published
  - workbench_moderation.moderation_state_transition.needs_review_archive
  - workbench_moderation.moderation_state_transition.needs_review_draft
  - workbench_moderation.moderation_state_transition.needs_review_needs_review
  - workbench_moderation.moderation_state_transition.needs_review_published
  - workbench_moderation.moderation_state_transition.published_archived
  - workbench_moderation.moderation_state_transition.published_draft
  - workbench_moderation.moderation_state_transition.published_published
  - workbench_moderation.moderation_state_transition.restore_to_draft
  - workbench_moderation.moderation_state.unpublished
  - workbench_moderation.moderation_state_transition.archive_unpublished
  - workbench_moderation.moderation_state_transition.published_unpublished
  - workbench_moderation.moderation_state_transition.unpublished_archive
  - workbench_moderation.moderation_state_transition.unpublished_draft
  - workbench_moderation.moderation_state_transition.unpublished_needs_review
  - workbench_moderation.moderation_state_transition.unpublished_published
