<?php

/**
 * @file
 * Variables for various options used in theme settings form.
 */

$agency_groupings = array(
  'styles' => 'None (ny.gov colors)',
  'administration' => 'Administration',
  'business' => 'Business',
  'education' => 'Education',
  'health-human-services' => 'Health and Human Services',
  'local-regional-authorities' => 'Local and Regional authorities',
  'public-safety' => 'Public Safety',
  'recreation-environment' => 'Recreation and Environment',
  'statewide-elected-officials' => 'Statewide Elected Officials',
  'transportation-utilities' => 'Transportation and Utilities',
  'custom-ig' => 'Custom - Inspector General',
  'custom-jcope' => 'Custom - JCOPE',
);
