<?php

/**
 * @file
 * Accessing the hidden regions: page_top and page_bottom to insert unav.
 */

/**
 * Implements hook_theme().
 */
function webny_theme() {
  return array(
    'webny_unav' => array(
      'template' => 'webny-unav',
    ),
    'webny_ufooter' => array(
      'template' => 'webny-ufooter',
    ),
  );
}

/**
 * Implements hook_page_top().
 *
 * Add universal navigation to the top of the page automatically.
 */
function webny_unav_page_top(array &$page_top) {
  $page_top['webny_unav'] = array(
    '#theme' => 'webny-unav',
  );
}

/**
 * Implements hook_page_bottom().
 *
 * Add universal navigation to the bottom of the page automatically.
 */
function webny_unav_page_bottom(array &$page_bottom) {
  $page_bottom['webny_ufooter'] = array(
    '#theme' => 'webny-ufooter',
  );
}
