<?php
/**
 * @file
 *
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CloseModalDialogCommand;
use Drupal\Core\Ajax\RedirectCommand;


/**
 * Implements hook_views_exposed_form_alter().
 */
// function public_appeal_search_views_exposed_form_alter(&$form, $form_state, $form_id)
// {
//     if ($form_id = 'views-exposed-form-sales-listings-block-page') {
//     }

// }

