<?php

use Drupal\webny_document_content_type\DocumentFileUrl;

/**
 * Implements hook_link_alter().
 */
function webny_document_content_type_link_alter(&$variables) {
  _webny_document_content_type_rewrite_document_links_to_file($variables);
}

function _webny_document_content_type_rewrite_document_links_to_file(&$variables) {
  if (_webny_document_content_type_is_document_page_link($variables)) {
    $variables['url'] = \Drupal::service('webny_document_content_type.document_file_url')->getUrl($variables['options']['entity']);
  }
}

function _webny_document_content_type_is_document_page_link($variables) {
  return (
    isset($variables['options']['entity_type'])
    && $variables['options']['entity_type'] === 'node'
    && $variables['options']['entity']->bundle() === 'webny_document'
    && !($variables['url']->isExternal())
    && $variables['url']->getRouteName() === 'entity.node.canonical'
  );
}
