files:
  include: '**/*.s+(a|c)ss'
  ignore:
rules:
  # Extends
  extends-before-mixins: 0
  extends-before-declarations: 0
  placeholder-in-extend: 0
  placeholder-name-format: 0

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 0
  empty-line-between-blocks: 0
  single-line-per-selector: 0

  # Disallows
  no-debug: 0
  no-empty-rulesets: 0
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-warn: 0
  no-color-literals: 0
  no-color-keywords: 0
  no-duplicate-properties: 0
  no-css-comments: 0
  no-vendor-prefixes: 0
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-mergeable-selectors: 0

  # Style Guide
  indentation: 0
  leading-zero: 0
  nesting-depth: 0
  property-sort-order: 0
  quotes: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
  brace-style: 0
  variable-name-format: 0

  # Inner Spacing
  space-after-comma: 0
  space-before-colon: 0
  space-after-colon: 0
  space-before-brace: 0
  space-before-bang: 0
  space-after-bang: 0
  space-between-parens: 0

  # Final Items
  trailing-semicolon: 0
  final-newline: 0

  empty-line-between-blocks: 0
  single-line-per-selector: 0
  empty-args: 0

  nesting-depth:
  - 1
  - max-depth: 3



files:
  include: '**/*.s+(a|c)ss'
  ignore:
rules:
  # Extends
  extends-before-mixins: 0
  extends-before-declarations: 0
  placeholder-in-extend: 0
  placeholder-name-format: 0

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 0
  empty-line-between-blocks: 0
  single-line-per-selector: 0

  # Disallows
  no-debug: 0
  no-empty-rulesets: 0
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-warn: 0
  no-color-literals: 0
  no-color-keywords: 0
  no-duplicate-properties: 0
  no-css-comments: 0
  no-vendor-prefixes: 0
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-mergeable-selectors: 0

  # Style Guide
  indentation: 0
  leading-zero: 0
  nesting-depth: 0
  property-sort-order: 0
  quotes: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  force-attribute-nesting: 0
  brace-style: 0
  variable-name-format: 0

  # Inner Spacing
  space-after-comma: 0
  space-before-colon: 0
  space-after-colon: 0
  space-before-brace: 0
  space-before-bang: 0
  space-after-bang: 0
  space-between-parens: 0

  # Final Items
  trailing-semicolon: 0
  final-newline: 0

  empty-line-between-blocks: 0
  single-line-per-selector: 0
  empty-args: 0

  nesting-depth:
  - 1
  - max-depth: 3



