<?php

/**
 * @file
 * Demonstrates use of the Cron API in Drupal - hook_cron().
 */

/**
 * @defgroup public_appeal_sync: Cron
 */

/**
 * Implements hook_cron().
 *
 * We implement hook_cron() to do "background" processing. It gets called every
 * time the Drupal cron runs. We then decide what has to happen in response.
 */
function public_appeal_sync_cron()
{
  date_default_timezone_set('America/New_York');
  
  // At 23'o clock on Saturday
  if (date('N') == 6 && date('G') == 23) {
    $service = \Drupal::service('public_appeal_sync.import_json');
    $service->importJson(); 
  }

    // At 23PM, On Janary 28, every year
  if (date('n-j-G') == "1-28-23" &&  date('G') == 23) {
    $service = \Drupal::service('public_appeal_sync.purge_data');
    $service->purgeData();
  }
}
