<?php

/**
 * Implements hook_theme().
 */
function webny_unav_theme() {
    return array(
        'webny_unav_header' => array(
            'template' => 'webny-unav-header',
            'variables' => array(),
        ),
        'webny_unav_footer' => array(
            'template' => 'webny-unav-footer',
            'variables' => array(),
        ),
        'webny_alt_unav_header' => array(
          'template' => 'webny-alt-unav-header',
          'variables' => array(),
        ),
    );
}

/**
 * Implements hook_page_top().
 *
 * Add uNav header to the page_top region
 * automatically if Drupal variable webny_unav_auto is TRUE.
 * But don't add uNav if on an administrative page.
 */
function webny_unav_page_top(&$page_top) {
    // Skip menu if not Auto or on administrative page.
    $config = \Drupal::config('webny_unav.settings');
    $unav_auto = $config->get('webny_unav.webny_unav_auto');
    $alt_unav_auto = $config->get('webny_unav.webny_alt_unav_auto');
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
    // UNAV OFF, ALT UNAV OFF, IS ADMIN RETURN NOTHING
    if (($unav_auto == '0' && $alt_unav_auto == '0') || $is_admin) {
        return;
    // UNAV ON
    } else if ($unav_auto == '1') {
      $page_top['page_top']['webny_unav'] = array(
        '#weight' => -1000,
        '#theme' => 'webny_unav_header',
      );
    // ALT UNAV ON
    } else if ($alt_unav_auto == '1') {
      $page_top['page_top']['webny_unav'] = array(
        '#weight' => -1000,
        '#theme' => 'webny_alt_unav_header',
      );
    }
}

/** Implemtnet hook_page_bottom().
 *
 * Add uNav footer to the page_bottom region
 * automatically if Drupal variable webny_unav_auto is TRUE.
 * But don't add uNav if on an administrative page
 */
function webny_unav_page_bottom(&$page_bottom) {
    // Skip menu if not Auto or on administrative page.
    $config = \Drupal::config('webny_unav.settings');
    $unav_auto = $config->get('webny_unav.webny_unav_auto');
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
    if ($unav_auto == '0' || $is_admin) {
        return;
    }
    $page_bottom['page_bottom']['webny_unav'] = array(
        '#weight' => 1000,
        '#theme' => 'webny_unav_footer',
    );
}

/**
 * Function webny_unav_preprocess.
 */
function webny_unav_preprocess(&$variables) {
  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('webny_global_nav')) {
    $globalNavConfig = \Drupal::config('webny_global_nav.settings');
    $variables['agencyname'] = $globalNavConfig->get('webny_global_nav.agencyname');
  } else {
    $variables['agencyname'] = '';
  }

  $unavConfig = \Drupal::config('webny_unav.settings');
  $variables['gt'] = $unavConfig->get('webny_unav.webny_alt_unav_translate');
  $variables['gsa'] = $unavConfig->get('webny_unav.webny_alt_unav_search');
  $variables['gsa_client'] = $unavConfig->get('webny_unav.webny_alt_unav_search_client');
  $variables['gsa_collection'] = $unavConfig->get('webny_unav.webny_alt_unav_search_collection');
  $variables['gsa_proxy_stylesheet'] = $unavConfig->get('webny_unav.webny_alt_unav_search_proxy_stylesheet');
  $variables['alt_unav_image'] = $unavConfig->get('webny_unav.webny_alt_unav_image');
  $variables['site_name'] = \Drupal::config('system.site')->get('name');

  $variables['#attached']['library'][] = 'webny_unav/webny-unav';

}