<?php

/**
 * Implements hook_theme().
 */
function webny_unav_theme() {
    return array(
        'webny_unav_header_static' => array(
            'template' => 'webny-unav-header-static',
            'variables' => array(),
        ),
        'webny_unav_header_interactive' => array(
            'template' => 'webny-unav-header-interactive',
            'variables' => array(),
        ),
        'webny_unav_footer_static' => array(
            'template' => 'webny-unav-footer-static',
            'variables' => array(),
        ),
        'webny_unav_footer_interactive' => array(
            'template' => 'webny-unav-footer-interactive',
            'variables' => array(),
        ),
    );
}

/**
 * Implements hook_page_top().
 *
 * Add uNav header to the page_top region
 * automatically if Drupal variable webny_unav_auto is TRUE.
 * But don't add uNav if on an administrative page.
 */
function webny_unav_page_top(&$page_top) {
    // Skip menu if not Auto or on administrative page.
    $config = \Drupal::config('webny_unav.settings');
    $unav_auto = $config->get('webny_unav.webny_unav_auto');
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
    if ($unav_auto == '0' || $is_admin) {
        return;
    }

    switch ($config->get('webny_unav.webny_unav_interactive')) {
        case '0':
            $page_top['page_top']['webny_unav'] = array(
                '#weight' => -1000,
                '#theme' => 'webny_unav_header_static',
            );
            break;
        case '1':
            $page_top['page_top']['webny_unav'] = array(
                '#weight' => -1000,
                '#theme' => 'webny_unav_header_interactive',
            );
            break;
    }
}

/** Implemtnet hook_page_bottom().
 *
 * Add uNav footer to the page_bottom region
 * automatically if Drupal variable webny_unav_auto is TRUE.
 * But don't add uNav if on an administrative page
 */
function webny_unav_page_bottom(&$page_bottom) {
    // Skip menu if not Auto or on administrative page.
    $config = \Drupal::config('webny_unav.settings');
    $unav_auto = $config->get('webny_unav.webny_unav_auto');
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
    if ($unav_auto == '0' || $is_admin) {
        return;
    }

    switch ($config->get('webny_unav.webny_unav_interactive')) {
        case '0':
            $page_bottom['page_bottom']['webny_unav'] = array(
                '#weight' => 1000,
                '#theme' => 'webny_unav_footer_static',
            );
            break;
        case '1':
            $page_bottom['page_bottom']['webny_unav'] = array(
                '#weight' => 1000,
                '#theme' => 'webny_unav_footer_interactive',
            );
            break;
    }
}
