<?php

/**
 * @file
 * Contains webny_secondary_nav.module.
 */

use Drupal\Core\Link;
use Drupal\Component\Utility\Xss;
use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements webny_secondary_nav_help()
 */
function webny_secondary_nav_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.webny_secondary_nav':
      return t('Integrate Webny Secondary Navigation onto your Drupal site.');
  }
}

/**
 * Implements hook_theme().
 */
function webny_secondary_nav_theme() {

    $config = \Drupal::config('webny_secondary_nav.settings');

    $defaultPageChoice  = $config->get('webny_secondary_nav.defaultPageChoice');

    return array(
        'webny_secondary_nav_wysiwyg_area' => array(
            'template' => 'webny-secondary-nav-wysiwyg-area',
            'variables' => array(

            ),
        ),
        'webny_secondary_nav_links_area' => array(
            'template' => 'webny-secondary-nav-links-area',
            'variables' => array(
                'defaultPageChoice' => $defaultPageChoice,
            ),
        ),
    );
}


/**
 * Function webny_global_nav_preprocess.
 */
function webny_secondary_nav_preprocess(&$variables) {
  $variables['#attached']['library'][] = 'webny_secondary_nav/secondary-nav';
}
