#!/usr/bin/env bash
## Run blt setup commands to prepare your local site for
## development.
##
## Usage: fin init
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
# Initialize stack
fin project start

COMPOSER_PROCESS_TIMEOUT=2000
composer clear-cache
echo "Composer install..."
composer nuke
composer install

cd $PROJECT_ROOT
echo "Running blt commands..."
fin addon install blt
echo "Creating settings files..."
fin blt blt:init:settings
#fin exec blt:setup:settings
#fin exec vendor/acquia/blt/bin/blt setup:settings
echo "Copying default local blt settings from .drush to blt folder..."
cp $PROJECT_ROOT/.docksal/lib/docksal.local.blt.yml $PROJECT_ROOT/blt/local.blt.yml
echo "Copying blt.yml and ignore-existing.txt from .docksal folder to blt and scripts folders respectivelu because sometimes installation replaces this file..."
cp $PROJECT_ROOT/.docksal/lib/blt.yml $PROJECT_ROOT/blt/blt.yml
cp $PROJECT_ROOT/.docksal/lib/local.drush.yml $DOCROOT_PATH/sites/default/settings/local.drush.yml
cp $PROJECT_ROOT/.docksal/lib/ignore-existing.txt $PROJECT_ROOT/scripts/blt/ignore-existing.txt
echo "Copying default local.settings.php file..."
cp $PROJECT_ROOT/.docksal/lib/docksal.local.settings.php $DOCROOT_PATH/sites/default/settings/local.settings.php
echo "Executing blt setup..."
fin blt setup -D setup.strategy=install
#fin exec vendor/acquia/blt/bin/blt setup:drupal:install
#fin exec vendor/acquia/blt/bin/blt setup
echo "Copying default local drush to local drush..."
cp $DOCROOT_PATH/sites/default/local.drush.yml $PROJECT_ROOT/local.drush.yml