<?php

/**
 * @file
 * Variables for various options used in theme settings form.
 */

$agency_groupings = array(
  'styles' => 'None (ny.gov colors)',
  'themes/administration' => 'Administration',
  'themes/business' => 'Business',
  'themes/education' => 'Education',
  'themes/health-human-services' => 'Health and Human Services',
  'themes/local-regional-authorities' => 'Local and Regional authorities',
  'themes/public-safety' => 'Public Safety',
  'themes/recreation-environment' => 'Recreation and Environment',
  'themes/statewide-elected-officials' => 'Statewide Elected Officials',
  'themes/transportation-utilities' => 'Transportation and Utilities',
);
