name: 'Workflow Basic Configuration'
description: "Basic configuration for Workbench Moderation.\r\nAdds 3 new Roles: Workflow author, Workflow approver, Workflow publisher\r\nUses default moderation states:  Draft, Needs Review, Published, Archived\r\nUses default transitions, deletes archived_published, edits description on 3, and adds 3 transitions\r\nApplies permissions for Workflow author,  Workflow publisher.  Workflow approver is a role for more complex workflow\r\n"
type: module
core: 8.x
dependencies:
  - workbench_moderation
package: WebNY
