<?php
/**
 * @file
 * Install, update and uninstall functions for the webny platform.
 */


/**
 * Implements hook_install().
 *
 * Performs actions to set up configuration.
 *
 * @see system_install()
 */
function webny_configuration_install() {

}

/**
 * Implements hook_update_n().
 *
 * Sample for demo only.
 *
 */

/*function webny_configuration_update_8000() {
  \Drupal::service('module_installer')
      ->install(['module1']);
}*/
